var annotated_dup =
[
    [ "Armes", "class_armes.html", "class_armes" ],
    [ "Barre_de_vie", "class_barre__de__vie.html", "class_barre__de__vie" ],
    [ "Base", "class_base.html", "class_base" ],
    [ "Boss", "class_boss.html", "class_boss" ],
    [ "Boss_summoner", "class_boss__summoner.html", "class_boss__summoner" ],
    [ "Ennemis", "class_ennemis.html", "class_ennemis" ],
    [ "Explosion", "class_explosion.html", "class_explosion" ],
    [ "Frame", "class_frame.html", "class_frame" ],
    [ "Gestion_input", "class_gestion__input.html", "class_gestion__input" ],
    [ "Gestion_son", "class_gestion__son.html", "class_gestion__son" ],
    [ "Guardian", "class_guardian.html", "class_guardian" ],
    [ "Gui", "class_gui.html", "class_gui" ],
    [ "Mob_mushroom", "class_mob__mushroom.html", "class_mob__mushroom" ],
    [ "Mob_skeleton", "class_mob__skeleton.html", "class_mob__skeleton" ],
    [ "Mob_slime", "class_mob__slime.html", "class_mob__slime" ],
    [ "Niveau", "class_niveau.html", "class_niveau" ],
    [ "Projectile_basique", "class_projectile__basique.html", "class_projectile__basique" ],
    [ "Projectile_corrosif", "class_projectile__corrosif.html", "class_projectile__corrosif" ],
    [ "Projectile_explosif", "class_projectile__explosif.html", "class_projectile__explosif" ],
    [ "Projectile_lourd", "class_projectile__lourd.html", "class_projectile__lourd" ],
    [ "Projectile_rapide", "class_projectile__rapide.html", "class_projectile__rapide" ],
    [ "Projectiles", "class_projectiles.html", "class_projectiles" ],
    [ "Weapon_blaster_basique", "class_weapon__blaster__basique.html", "class_weapon__blaster__basique" ],
    [ "Weapon_blaster_corrosif", "class_weapon__blaster__corrosif.html", "class_weapon__blaster__corrosif" ],
    [ "Weapon_blaster_explosif", "class_weapon__blaster__explosif.html", "class_weapon__blaster__explosif" ],
    [ "Weapon_blaster_minigun", "class_weapon__blaster__minigun.html", "class_weapon__blaster__minigun" ],
    [ "Weapon_blaster_sniper", "class_weapon__blaster__sniper.html", "class_weapon__blaster__sniper" ]
];